In [1]:
import os 
import sys 
base_path = os.path.dirname(os.getcwd())
if base_path not in sys.path:
    sys.path.append(base_path)

In [3]:
from models.hifigan.hifiwrapper import HifiGan

In [5]:
hifi_ckpt = r"d:\research\ckpt\g_02500000.pt"

In [2]:
import torch

In [4]:
conformer_ckpt = r"D:\research\speech\work\wavlm_kmeans_hifi\ckpt\step160000_model.pth"
ckpt_dict = torch.load(conformer_ckpt, map_location="cpu")

In [13]:
state_dict = ckpt_dict['model_state_dict']

In [ ]:
torch.save(state_dict, "step160000_model.pth")

In [7]:
res = {"model_state_dict": ckpt_dict}
torch.save(res, "step_16000.pth")

In [9]:
ckpt = torch.load("step_16000.pth", map_location="cpu")

In [11]:
ckpt['model_state_dict']

OrderedDict([('mask_emb', tensor([0., 0., 0.,  ..., 0., 0., 0.])),
             ('kmeans._float_tensor', tensor([0.])),
             ('conformer.conformer_layers.0.ffn1.sequential.0.weight',
              tensor([0.5032, 0.5322, 0.4373,  ..., 0.5625, 0.3719, 0.4244])),
             ('conformer.conformer_layers.0.ffn1.sequential.0.bias',
              tensor([ 0.0247, -0.0721,  0.0572,  ...,  0.0094,  0.0104,  0.1283])),
             ('conformer.conformer_layers.0.ffn1.sequential.1.weight',
              tensor([[ 0.0106, -0.0045, -0.0115,  ..., -0.0089,  0.0101,  0.0337],
                      [ 0.0181,  0.0070,  0.0021,  ...,  0.0290,  0.0065, -0.0116],
                      [ 0.0163, -0.0180, -0.0278,  ...,  0.0004,  0.0050, -0.0165],
                      ...,
                      [ 0.0270, -0.0325,  0.0205,  ..., -0.0207,  0.0166,  0.0112],
                      [ 0.0047,  0.0059,  0.0217,  ...,  0.0453,  0.0113,  0.0113],
                      [-0.0099,  0.0201,  0.0008,  ...,  0